<?php
// privacy-policy.php — GMHOMEZ
require_once __DIR__.'/lib/render.php';
render_header('Privacy Policy');
$base = render_base_url();
?>
<style>
  .doc{max-width:900px;margin:16px auto 28px}
  .doc header{margin:10px 0 14px}
  .doc h1{font-size:32px;margin:0}
  .doc .updated{color:#64748b;margin-top:4px}
  .toc{border:1px solid #e5e7eb;border-radius:12px;padding:14px;background:#fff;margin:14px 0 22px}
  .toc b{display:block;margin-bottom:6px}
  .toc a{display:block;color:#0f172a;text-decoration:none;margin:6px 0}
  .doc h2{margin:22px 0 10px;font-size:22px}
  .doc h3{margin:14px 0 8px;font-size:18px}
  .doc p{margin:10px 0}
  .doc ul{margin:8px 0 12px 20px}
  .doc code{background:#f3f4f6;border:1px solid #e5e7eb;padding:1px 6px;border-radius:6px}
  .note{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin:12px 0}
</style>

<article class="doc">
  <header>
    <h1>Privacy Policy</h1>
    <div class="updated">Last updated: September 17, 2025</div>
  </header>

  <p>
    This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
    information when you use the Service and tells you about your privacy rights and how the law protects you.
    By using the Service, you agree to the collection and use of information in accordance with this policy.
  </p>

  <div class="toc">
    <b>On this page</b>
    <a href="#interpretation">Interpretation &amp; Definitions</a>
    <a href="#collect">Collecting &amp; Using Your Personal Data</a>
    <a href="#cookies">Tracking Technologies &amp; Cookies</a>
    <a href="#use">Use of Your Personal Data</a>
    <a href="#share">Sharing of Your Personal Data</a>
    <a href="#retention">Retention</a>
    <a href="#transfer">International Transfers</a>
    <a href="#delete">Delete Your Personal Data</a>
    <a href="#disclosure">Disclosure</a>
    <a href="#security">Security</a>
    <a href="#processors">Third-party Service Providers</a>
    <a href="#children">Children’s Privacy</a>
    <a href="#links">Links to Other Websites</a>
    <a href="#changes">Changes to this Policy</a>
    <a href="#contact">Contact Us</a>
  </div>

  <h2 id="interpretation">Interpretation &amp; Definitions</h2>
  <h3>Interpretation</h3>
  <p>
    Words with initial capital letters have meanings defined below. The following definitions shall have the same
    meaning regardless of whether they appear in singular or plural.
  </p>

  <h3>Definitions</h3>
  <ul>
    <li><b>Account</b> means a unique account created for you to access our Service or parts of our Service.</li>
    <li><b>Affiliate</b> means an entity that controls, is controlled by, or is under common control with a party,
      where “control” means ownership of 50% or more of the shares, equity interest, or other securities entitled
      to vote for election of directors or other managing authority.</li>
    <li><b>Company</b> (referred to as “the Company”, “we”, “us” or “our”) refers to
      <b>GAYATHRI D N</b>, 111, 4th Floor, HSR Layout Sector 2.</li>
    <li><b>Cookies</b> are small files placed on your device that store details of your browsing history and other
      information.</li>
    <li><b>Country</b> refers to: Karnataka, India.</li>
    <li><b>Device</b> means any device that can access the Service (e.g., computer, cellphone, tablet).</li>
    <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
    <li><b>Service</b> refers to the Website.</li>
    <li><b>Service Provider</b> means any natural or legal person who processes data on behalf of the Company.</li>
    <li><b>Usage Data</b> refers to data collected automatically, generated by the use of the Service or from the
      Service infrastructure itself (e.g., duration of a page visit).</li>
    <li><b>Website</b> refers to <b>GMHOMEZ</b>, accessible at <a href="http://gmhomez.in/" target="_blank" rel="noopener">http://gmhomez.in/</a>.</li>
    <li><b>You</b> means the individual accessing or using the Service, or the company or other legal entity on
      behalf of which that individual is accessing or using the Service, as applicable.</li>
  </ul>

  <h2 id="collect">Collecting &amp; Using Your Personal Data</h2>
  <h3>Types of Data Collected</h3>
  <p><b>Personal Data.</b> While using our Service, we may ask you to provide certain personally identifiable
     information that can be used to contact or identify you, including but not limited to:</p>
  <ul>
    <li>Email address</li>
    <li>First and last name</li>
    <li>Phone number</li>
    <li>Address, State, Province, ZIP/Postal code, City</li>
    <li>Usage Data</li>
  </ul>

  <h3>Usage Data</h3>
  <p>
    Usage Data is collected automatically and may include your Device’s IP address, browser type and version, pages
    visited, time and date of visit, time spent on pages, unique device identifiers and other diagnostic data. If you
    access the Service via a mobile device, we may collect similar information specific to your device and OS.
  </p>

  <h2 id="cookies">Tracking Technologies &amp; Cookies</h2>
  <p>
    We use Cookies and similar tracking technologies (beacons, tags, scripts) to track activity on our Service and
    store certain information. Cookies may be “Persistent” (remain when you go offline) or “Session” (deleted when
    you close your browser).
  </p>
  <h3>We use the following types of Cookies</h3>
  <ul>
    <li><b>Necessary / Essential Cookies</b> (Session). Used to provide core functionality and authenticate users.</li>
    <li><b>Cookies Policy / Notice Acceptance Cookies</b> (Persistent). Used to remember your cookie preferences.</li>
    <li><b>Functionality Cookies</b> (Persistent). Used to remember choices (e.g., language or login details).</li>
  </ul>
  <p class="note">
    You can instruct your browser to refuse Cookies or indicate when a Cookie is being sent. If you do not accept
    Cookies, some parts of the Service may not function properly.
  </p>

  <h2 id="use">Use of Your Personal Data</h2>
  <p>The Company may use Personal Data for the following purposes:</p>
  <ul>
    <li><b>To provide and maintain our Service</b>, including monitoring usage.</li>
    <li><b>To manage your Account</b> as a registered user.</li>
    <li><b>For the performance of a contract</b> (purchase or other agreements made via the Service).</li>
    <li><b>To contact you</b> by email, phone, SMS, or push notifications regarding updates or information related to
        the Service, including security updates.</li>
    <li><b>To provide you with news and offers</b> regarding goods, services, and events similar to those you have
        purchased or enquired about (unless you opt out).</li>
    <li><b>To manage your requests</b> (support or other queries).</li>
    <li><b>For business transfers</b> (e.g., merger, acquisition, restructuring).</li>
    <li><b>For other purposes</b>, such as analytics, usage trends, campaign effectiveness, and improving our Service
        and user experience.</li>
  </ul>

  <h2 id="share">Sharing of Your Personal Data</h2>
  <ul>
    <li><b>With Service Providers</b> to monitor and analyze the Service, or to contact you.</li>
    <li><b>For business transfers</b> in connection with or during negotiations of a merger, sale of assets,
        financing, or acquisition.</li>
    <li><b>With Affiliates</b> (we require them to honor this Privacy Policy).</li>
    <li><b>With business partners</b> to offer you certain products, services, or promotions.</li>
    <li><b>With other users</b> when information is shared in public areas of the Service.</li>
    <li><b>With your consent</b> for any other purpose.</li>
  </ul>

  <h2 id="retention">Retention of Your Personal Data</h2>
  <p>
    We retain Personal Data only as long as necessary for the purposes set out in this Privacy Policy, to comply with
    legal obligations, resolve disputes, and enforce agreements. Usage Data is generally retained for a shorter
    period unless needed for security, functionality improvements, or legal obligations.
  </p>

  <h2 id="transfer">International Transfers</h2>
  <p>
    Your information may be processed at our offices and other locations where parties involved in processing are
    located. This may mean transfers to jurisdictions with different data protection laws. We take reasonable steps
    to ensure your data is treated securely and in accordance with this policy, and that transfers occur only where
    adequate safeguards are in place.
  </p>

  <h2 id="delete">Delete Your Personal Data</h2>
  <p>
    You may request deletion of Personal Data we hold about you. If the Service provides self-service deletion,
    you can use that feature. You may also update, amend, or delete information by signing into your Account (if
    applicable) or by contacting us. We may retain certain information where we have a legal obligation or lawful basis.
  </p>

  <h2 id="disclosure">Disclosure of Your Personal Data</h2>
  <h3>Business Transactions</h3>
  <p>If we are involved in a merger, acquisition, or asset sale, your Personal Data may be transferred with notice
     before it becomes subject to a different policy.</p>
  <h3>Law Enforcement &amp; Legal Requirements</h3>
  <p>
    We may disclose your Personal Data if required by law or in response to valid requests by public authorities, and
    in good faith to (i) comply with a legal obligation, (ii) protect and defend our rights or property,
    (iii) prevent or investigate possible wrongdoing, (iv) protect the personal safety of users or the public,
    or (v) protect against legal liability.
  </p>

  <h2 id="security">Security of Your Personal Data</h2>
  <p>
    We use commercially acceptable means to protect your Personal Data, but no method of transmission over the
    Internet or electronic storage is 100% secure. We cannot guarantee absolute security.
  </p>

  <h2 id="processors">Third-party Service Providers</h2>
  <p>
    Service Providers we use may have access to your Personal Data solely to perform tasks on our behalf and are
    obligated not to disclose or use it for other purposes.
  </p>
  <h3>Usage, Performance &amp; Miscellaneous</h3>
  <p><b>Google Places.</b> We may use Google Places to return information about places through HTTP requests. Google
    may collect information from you and your device for security purposes. For details, see Google’s privacy policy:
    <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener">https://www.google.com/intl/en/policies/privacy/</a>.
  </p>

  <h2 id="children">Children’s Privacy</h2>
  <p>
    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
    information from children under 13. If you are a parent or guardian and believe your child has provided Personal
    Data, please contact us so we can take appropriate action.
  </p>

  <h2 id="links">Links to Other Websites</h2>
  <p>
    Our Service may contain links to third-party websites not operated by us. We recommend reviewing the privacy
    policy of every site you visit. We have no control over and assume no responsibility for the content, privacy
    policies, or practices of third-party sites or services.
  </p>

  <h2 id="changes">Changes to this Privacy Policy</h2>
  <p>
    We may update this Privacy Policy from time to time. We will post the new Privacy Policy on this page and update
    the “Last updated” date. Where required, we will also notify you by email and/or a prominent notice on the Service
    before changes take effect.
  </p>

  <h2 id="contact">Contact Us</h2>
  <p>If you have any questions about this Privacy Policy, you can contact us:</p>
  <ul>
    <li>By email: <a href="mailto:info@gmhomez.in">info@gmhomez.in</a></li>
    <li>On the web: <a href="http://gmhomez.in/" target="_blank" rel="noopener">http://gmhomez.in/</a></li>
  </ul>

  

  <p><a href="<?= h($base) ?>/" style="text-decoration:underline">← Back to Home</a></p>
</article>

<?php render_footer(); ?>
