name: AWS cred check

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I?
        run: |
          set -eux
          aws sts get-caller-identity
          echo "Region (env): ${AWS_REGION:-${AWS_DEFAULT_REGION:-unset}}"
          aws configure get region || true
