      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: gmhomezzz
          environment_name: Gmhomez-env11
          region: us-east-2
          version_label: v-${{ github.run_number }}
          deployment_package: app.zip
