name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EB_APPLICATION: ${{ secrets.EB_APPLICATION }}
      EB_ENVIRONMENT: ${{ secrets.EB_ENVIRONMENT }}
      EB_PLATFORM: PHP 8.4 running on 64bit Amazon Linux 2023/4.7.5

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install EB CLI
        run: |
          pip install --upgrade awsebcli
          eb --version
          aws --version

      - name: Initialize EB (non-interactive)
        run: |
          set -eux
          eb init "$EB_APPLICATION" --region "${{ secrets.AWS_REGION }}" --platform "$EB_PLATFORM" --verbose
          eb use "$EB_ENVIRONMENT" --verbose

      - name: Deploy
        run: |
          set -eux
          eb deploy --staged --verbose
